version:  '3'

services:
  solid:
    build:
      dockerfile: ./docker/solid.dockerfile
      context: .
    image: solid/ruby
    container_name: solid
    volumes: 
      - ./app:/usr/src/app
    tty: true
