name: Lint Rubocop

on: 
  push: 
    branch: [main, develop]
  pull_request:
    branch: main

jobs:
  rspec-with-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - run: bundle install
      - run: rubocop -a app/