name: Unit Tests

on:
  workflow_run:
    worflows: ['Lint Rubocop']
    branches: [main, develop]
    type:
      - completed

jobs:
  rspec-with-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - run: bundle install
      - run: echo "Dir.glob('.app/test/test_*.rb').each { |file| require file}" | ruby
